/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.openepics.names.service;

import java.util.Set;
import javax.ws.rs.core.Application;

/**
 *
 * @author Vasu V <vuppala@frib.msu.org>
 */
@javax.ws.rs.ApplicationPath("/rest/v0")
public class NameRestService extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        return getRestResourceClasses();
    }

    /**
     * Do not modify this method. It is automatically generated by NetBeans REST support.
     */
    private Set<Class<?>> getRestResourceClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        resources.add(org.openepics.names.service.NameElementCategoryResource.class);
        resources.add(org.openepics.names.service.NameElementResource.class);
        resources.add(org.openepics.names.service.NameEventResource.class);
        resources.add(org.openepics.names.service.NameReleaseResource.class);
        return resources;
    }
    
}
